import { NextResponse } from "next/server";
import { isOwnerAuthConfigured } from "@/lib/owner-auth";
import { safeOwnerNextPath } from "@/lib/owner-auth-redirect";
import { createClient } from "@/lib/supabase/server";

export const runtime = "nodejs";
export const dynamic = "force-dynamic";

function loginErrorUrl(origin: string, next: string): URL {
  const login = new URL("/login", origin);
  login.searchParams.set("next", next);
  login.searchParams.set("error", "magic_link");
  return login;
}

/**
 * Exchanges either the PKCE code generated by the dedicated project's built-in
 * email flow or the legacy token-hash callback form.
 *
 * The hook renders verification URLs as `/auth/callback?token_hash=...&type=...`.
 * Completing the exchange server-side lets @supabase/ssr persist the session
 * cookies before the browser is redirected into the protected owner surface.
 */
export async function GET(request: Request) {
  const requestUrl = new URL(request.url);
  const next = safeOwnerNextPath(requestUrl.searchParams.get("next"));
  const code = requestUrl.searchParams.get("code");
  const tokenHash = requestUrl.searchParams.get("token_hash");
  const type = requestUrl.searchParams.get("type");

  if (!isOwnerAuthConfigured() || (!code && (!tokenHash || type !== "magiclink"))) {
    return NextResponse.redirect(loginErrorUrl(requestUrl.origin, next));
  }

  try {
    const supabase = await createClient();
    const { error } = code
      ? await supabase.auth.exchangeCodeForSession(code)
      : await supabase.auth.verifyOtp({ token_hash: tokenHash!, type: "magiclink" });
    if (error) {
      return NextResponse.redirect(loginErrorUrl(requestUrl.origin, next));
    }
  } catch {
    return NextResponse.redirect(loginErrorUrl(requestUrl.origin, next));
  }

  return NextResponse.redirect(new URL(next, requestUrl.origin));
}
