/**
 * Hardcoded literal fixtures for the owner dashboard.
 *
 * Deliberately NOT computed from `computeProgress`/`buildFlow` at module
 * scope: every field here is a literal so the fixture set can be shaped to
 * exercise every alert rule and every driver status at least once, and so
 * server and client render byte-identical output (no Date.now(), no
 * Math.random(), no relative-time math — every timestamp is an explicit
 * Date.UTC(...) call with literal arguments).
 *
 * Anchor era: mid-August 2026, one Model Y, one continuous odometer/battery
 * history across the 6 completed trips + the 1 active trip. Module ids and
 * checklist ids are the real ones from lib/content.ts (MODULES / CHECKLIST) —
 * do not invent new ones here.
 */

import type { ChargingSession, Driver, Trip } from "./types";

const ts = (y: number, m: number, d: number, h = 0, min = 0) => Date.UTC(y, m - 1, d, h, min);

/* ── Drivers ──────────────────────────────────────────────────────────────
 * Statuses covered: ready (drv-01, drv-05), in-progress (drv-02, drv-06),
 * not-started (drv-03, drv-07), stalled (drv-04, drv-08).
 */

export const MOCK_DRIVERS: Driver[] = [
  {
    id: "drv-01",
    name: "Marcus Webb",
    email: "marcus.webb@gmail.com",
    source: "mock",
    progress: {
      stepId: "done",
      pct: 100,
      isDone: true,
      completed: ["phone-key", "charging-this-car", "house-rules", "return-trip", "help"],
      checklist: {
        "tesla-app": true,
        "phone-key": true,
        charging: true,
        "house-rules": true,
        contacts: true,
        "one-pedal": true,
      },
      moduleTotal: 5,
      checklistDone: 6,
      checklistTotal: 6,
      requiredChecklistDone: 5,
      requiredChecklistTotal: 5,
      experience: "owner",
      pathMode: "essentials",
      startedAt: ts(2026, 6, 1, 9, 10),
      guestName: "Marcus Webb",
      updatedAt: ts(2026, 6, 1, 9, 42),
    },
  },
  {
    id: "drv-02",
    name: "Priya Natarajan",
    email: "priya.nat88@outlook.com",
    source: "mock",
    progress: {
      stepId: "charging-this-car",
      pct: 44,
      isDone: false,
      completed: ["phone-key"],
      checklist: {
        "tesla-app": true,
        "phone-key": true,
        charging: false,
        "house-rules": false,
        contacts: false,
        "one-pedal": false,
      },
      moduleTotal: 5,
      checklistDone: 2,
      checklistTotal: 6,
      requiredChecklistDone: 2,
      requiredChecklistTotal: 5,
      experience: "account",
      pathMode: "essentials",
      startedAt: ts(2026, 8, 9, 20, 5),
      guestName: "Priya Natarajan",
      updatedAt: ts(2026, 8, 11, 21, 30),
    },
  },
  {
    id: "drv-03",
    name: "Diego Fuentes",
    email: "d.fuentes.sf@gmail.com",
    source: "mock",
    progress: null,
  },
  {
    id: "drv-04",
    name: "Hannah Kim",
    email: "hannah.kim.travel@gmail.com",
    source: "mock",
    progress: {
      stepId: "house-rules",
      pct: 56,
      isDone: false,
      completed: ["phone-key"],
      checklist: {
        "tesla-app": true,
        "phone-key": true,
        charging: true,
        "house-rules": false,
        contacts: false,
        "one-pedal": false,
      },
      moduleTotal: 5,
      checklistDone: 3,
      checklistTotal: 6,
      requiredChecklistDone: 3,
      requiredChecklistTotal: 5,
      experience: "account",
      pathMode: "essentials",
      startedAt: ts(2026, 8, 4, 12, 0),
      guestName: "Hannah Kim",
      updatedAt: ts(2026, 8, 5, 8, 15),
    },
  },
  {
    id: "drv-05",
    name: "Olivia Chen",
    email: "olivia.chen91@yahoo.com",
    source: "mock",
    progress: {
      stepId: "done",
      pct: 100,
      isDone: true,
      completed: [
        "phone-key",
        "driving-basics",
        "the-screen",
        "autopilot",
        "charging-basics",
        "charging-this-car",
        "house-rules",
        "return-trip",
        "help",
      ],
      checklist: {
        "tesla-app": true,
        "phone-key": true,
        charging: true,
        "house-rules": true,
        contacts: true,
        "one-pedal": true,
      },
      moduleTotal: 9,
      checklistDone: 6,
      checklistTotal: 6,
      requiredChecklistDone: 5,
      requiredChecklistTotal: 5,
      experience: "new",
      pathMode: "full",
      startedAt: ts(2026, 6, 13, 18, 0),
      guestName: "Olivia Chen",
      updatedAt: ts(2026, 6, 14, 19, 5),
    },
  },
  {
    id: "drv-06",
    name: "Ben Osei",
    email: "ben.osei@proton.me",
    source: "mock",
    progress: {
      stepId: "autopilot",
      pct: 50,
      isDone: false,
      completed: ["phone-key", "driving-basics", "the-screen"],
      checklist: {
        "tesla-app": true,
        "phone-key": true,
        charging: false,
        "house-rules": false,
        contacts: false,
        "one-pedal": false,
      },
      moduleTotal: 9,
      checklistDone: 2,
      checklistTotal: 6,
      requiredChecklistDone: 2,
      requiredChecklistTotal: 5,
      experience: "new",
      pathMode: "full",
      startedAt: ts(2026, 8, 10, 16, 0),
      guestName: "Ben Osei",
      updatedAt: ts(2026, 8, 11, 22, 10),
    },
  },
  {
    id: "drv-07",
    name: "Rachel Torres",
    email: "rachel.torres.nyc@gmail.com",
    source: "mock",
    progress: null,
  },
  {
    id: "drv-08",
    name: "Jamal Whitfield",
    email: "jamal.whitfield@icloud.com",
    source: "mock",
    progress: {
      stepId: "return-trip",
      pct: 67,
      isDone: false,
      completed: ["phone-key", "charging-this-car"],
      checklist: {
        "tesla-app": true,
        "phone-key": true,
        charging: true,
        "house-rules": true,
        contacts: false,
        "one-pedal": false,
      },
      moduleTotal: 5,
      checklistDone: 4,
      checklistTotal: 6,
      requiredChecklistDone: 4,
      requiredChecklistTotal: 5,
      experience: "owner",
      pathMode: "essentials",
      startedAt: ts(2026, 8, 3, 10, 0),
      guestName: "Jamal Whitfield",
      updatedAt: ts(2026, 8, 4, 11, 45),
    },
  },
];

/* ── Trips ────────────────────────────────────────────────────────────────
 * One car, one continuous odometer/battery history. 6 completed, 1 active,
 * 4 upcoming (trip-11 unassigned, reserved for the ?trip= demo link).
 */

export const MOCK_TRIPS: Trip[] = [
  {
    id: "trip-01",
    driverId: "drv-01",
    status: "completed",
    startAt: ts(2026, 6, 3, 10, 0),
    endAt: ts(2026, 6, 6, 17, 0),
    odometerStartMi: 18432.6,
    odometerEndMi: 18711.2,
    batteryStartPct: 92,
    batteryEndPct: 48, // below the 80% return policy
    chargingSessionIds: ["chg-01", "chg-02", "chg-03"],
  },
  {
    id: "trip-02",
    driverId: "drv-05",
    status: "completed",
    startAt: ts(2026, 6, 15, 9, 30),
    endAt: ts(2026, 6, 17, 16, 0),
    odometerStartMi: 18711.2,
    odometerEndMi: 18889.4,
    batteryStartPct: 88,
    batteryEndPct: 55,
    chargingSessionIds: ["chg-04"],
  },
  {
    id: "trip-03",
    driverId: "drv-02",
    status: "completed",
    startAt: ts(2026, 6, 28, 11, 0),
    endAt: ts(2026, 7, 2, 18, 30),
    odometerStartMi: 18889.4,
    odometerEndMi: 19240.1,
    batteryStartPct: 95,
    batteryEndPct: 30, // below the 80% return policy
    chargingSessionIds: ["chg-05", "chg-06", "chg-07", "chg-08"],
  },
  {
    id: "trip-04",
    driverId: "drv-06",
    status: "completed",
    startAt: ts(2026, 7, 10, 8, 45),
    endAt: ts(2026, 7, 12, 15, 0),
    odometerStartMi: 19240.1,
    odometerEndMi: 19410.8,
    batteryStartPct: 90,
    batteryEndPct: 85,
    chargingSessionIds: ["chg-09"],
  },
  {
    id: "trip-05",
    driverId: "drv-01",
    status: "completed",
    startAt: ts(2026, 7, 22, 10, 15),
    endAt: ts(2026, 7, 25, 17, 30),
    odometerStartMi: 19410.8,
    odometerEndMi: 19702.3,
    batteryStartPct: 91,
    batteryEndPct: 60,
    chargingSessionIds: ["chg-10", "chg-11", "chg-12", "chg-13"],
  },
  {
    id: "trip-06",
    driverId: "drv-05",
    status: "completed",
    startAt: ts(2026, 8, 1, 9, 0),
    endAt: ts(2026, 8, 4, 16, 15),
    odometerStartMi: 19702.3,
    odometerEndMi: 19855.0,
    batteryStartPct: 89,
    batteryEndPct: 91,
    chargingSessionIds: ["chg-14", "chg-15"],
  },
  {
    id: "trip-07",
    driverId: "drv-02",
    status: "active",
    startAt: ts(2026, 8, 10, 9, 0),
    endAt: ts(2026, 8, 14, 17, 0),
    odometerStartMi: 19855.0,
    odometerEndMi: null,
    batteryStartPct: 82,
    batteryEndPct: null,
    chargingSessionIds: ["chg-16", "chg-17"],
  },
  {
    id: "trip-08",
    driverId: "drv-03",
    status: "upcoming",
    startAt: ts(2026, 8, 13, 9, 0),
    endAt: ts(2026, 8, 16, 17, 0),
    odometerStartMi: null,
    odometerEndMi: null,
    batteryStartPct: null,
    batteryEndPct: null,
    chargingSessionIds: [],
  },
  {
    id: "trip-09",
    driverId: "drv-06",
    status: "upcoming",
    startAt: ts(2026, 8, 13, 6, 0),
    endAt: ts(2026, 8, 15, 12, 0),
    odometerStartMi: null,
    odometerEndMi: null,
    batteryStartPct: null,
    batteryEndPct: null,
    chargingSessionIds: [],
  },
  {
    id: "trip-10",
    driverId: "drv-04",
    status: "upcoming",
    startAt: ts(2026, 8, 18, 10, 0),
    endAt: ts(2026, 8, 21, 17, 0),
    odometerStartMi: null,
    odometerEndMi: null,
    batteryStartPct: null,
    batteryEndPct: null,
    chargingSessionIds: [],
  },
  {
    id: "trip-11",
    driverId: null, // unassigned — reserved for the ?trip= demo link
    status: "upcoming",
    startAt: ts(2026, 8, 20, 10, 0),
    endAt: ts(2026, 8, 23, 17, 0),
    odometerStartMi: null,
    odometerEndMi: null,
    batteryStartPct: null,
    batteryEndPct: null,
    chargingSessionIds: [],
  },
];

/* ── Charging sessions ───────────────────────────────────────────────────
 * Superchargers ($0.36–0.52/kWh, real CA station names) + home/public L2
 * ($0.14–0.20/kWh). Every timestamp sits inside its trip's window.
 */

export const MOCK_CHARGING_SESSIONS: ChargingSession[] = [
  {
    id: "chg-01",
    tripId: "trip-01",
    startedAt: ts(2026, 6, 3, 14, 10),
    endedAt: ts(2026, 6, 3, 14, 42),
    location: "Supercharger - Gilroy, CA",
    isSupercharger: true,
    kWhAdded: 32.4,
    costUsd: 15.16,
  },
  {
    id: "chg-02",
    tripId: "trip-01",
    startedAt: ts(2026, 6, 4, 19, 5),
    endedAt: ts(2026, 6, 4, 19, 50),
    location: "Supercharger - Kettleman City, CA",
    isSupercharger: true,
    kWhAdded: 41.8,
    costUsd: 20.06,
  },
  {
    id: "chg-03",
    tripId: "trip-01",
    startedAt: ts(2026, 6, 5, 21, 0),
    endedAt: ts(2026, 6, 6, 4, 0),
    location: "Home charging (garage)",
    isSupercharger: false,
    kWhAdded: 18.2,
    costUsd: 3.28,
  },
  {
    id: "chg-04",
    tripId: "trip-02",
    startedAt: ts(2026, 6, 16, 22, 30),
    endedAt: ts(2026, 6, 17, 5, 30),
    location: "Home charging (garage)",
    isSupercharger: false,
    kWhAdded: 22.5,
    costUsd: 3.83,
  },
  {
    id: "chg-05",
    tripId: "trip-03",
    startedAt: ts(2026, 6, 29, 13, 0),
    endedAt: ts(2026, 6, 29, 13, 35),
    location: "Supercharger - Santa Nella, CA",
    isSupercharger: true,
    kWhAdded: 38.6,
    costUsd: 19.11,
  },
  {
    id: "chg-06",
    tripId: "trip-03",
    startedAt: ts(2026, 6, 30, 17, 45),
    endedAt: ts(2026, 6, 30, 18, 20),
    location: "Supercharger - San Mateo, CA",
    isSupercharger: true,
    kWhAdded: 35.1,
    costUsd: 16.85,
  },
  {
    id: "chg-07",
    tripId: "trip-03",
    startedAt: ts(2026, 7, 1, 12, 15),
    endedAt: ts(2026, 7, 1, 12, 50),
    location: "Supercharger - Gilroy, CA",
    isSupercharger: true,
    kWhAdded: 29.7,
    costUsd: 14.55,
  },
  {
    id: "chg-08",
    tripId: "trip-03",
    startedAt: ts(2026, 7, 1, 22, 0),
    endedAt: ts(2026, 7, 2, 6, 0),
    location: "Public L2 - City garage",
    isSupercharger: false,
    kWhAdded: 14.9,
    costUsd: 2.68,
  },
  {
    id: "chg-09",
    tripId: "trip-04",
    startedAt: ts(2026, 7, 11, 16, 0),
    endedAt: ts(2026, 7, 11, 16, 25),
    location: "Supercharger - Gilroy, CA",
    isSupercharger: true,
    kWhAdded: 12.3,
    costUsd: 5.9,
  },
  {
    id: "chg-10",
    tripId: "trip-05",
    startedAt: ts(2026, 7, 23, 12, 0),
    endedAt: ts(2026, 7, 23, 12, 35),
    location: "Supercharger - Kettleman City, CA",
    isSupercharger: true,
    kWhAdded: 33.9,
    costUsd: 16.27,
  },
  {
    id: "chg-11",
    tripId: "trip-05",
    startedAt: ts(2026, 7, 24, 9, 15),
    endedAt: ts(2026, 7, 24, 9, 50),
    location: "Supercharger - Santa Nella, CA",
    isSupercharger: true,
    kWhAdded: 30.2,
    costUsd: 14.95,
  },
  {
    id: "chg-12",
    tripId: "trip-05",
    startedAt: ts(2026, 7, 24, 20, 0),
    endedAt: ts(2026, 7, 25, 4, 0),
    location: "Home charging (garage)",
    isSupercharger: false,
    kWhAdded: 20.0,
    costUsd: 3.4,
  },
  {
    id: "chg-13",
    tripId: "trip-05",
    startedAt: ts(2026, 7, 25, 11, 30),
    endedAt: ts(2026, 7, 25, 12, 5),
    location: "Supercharger - Gilroy, CA",
    isSupercharger: true,
    kWhAdded: 27.4,
    costUsd: 13.32,
  },
  {
    id: "chg-14",
    tripId: "trip-06",
    startedAt: ts(2026, 8, 2, 15, 30),
    endedAt: ts(2026, 8, 2, 16, 10),
    location: "Supercharger - San Mateo, CA",
    isSupercharger: true,
    kWhAdded: 40.5,
    costUsd: 21.06,
  },
  {
    id: "chg-15",
    tripId: "trip-06",
    startedAt: ts(2026, 8, 3, 21, 0),
    endedAt: ts(2026, 8, 4, 5, 0),
    location: "Home charging (garage)",
    isSupercharger: false,
    kWhAdded: 16.4,
    costUsd: 2.79,
  },
  {
    id: "chg-16",
    tripId: "trip-07",
    startedAt: ts(2026, 8, 10, 18, 0),
    endedAt: ts(2026, 8, 10, 18, 40),
    location: "Supercharger - Gilroy, CA",
    isSupercharger: true,
    kWhAdded: 34.8,
    costUsd: 17.75,
  },
  {
    id: "chg-17",
    tripId: "trip-07",
    startedAt: ts(2026, 8, 11, 22, 0),
    endedAt: ts(2026, 8, 12, 5, 0),
    location: "Home charging (garage)",
    isSupercharger: false,
    kWhAdded: 19.6,
    costUsd: 3.33,
  },
];
